name: Generate posts.json

on:
  push:
    paths:
      - 'blog/posts/**.md'
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate posts.json
        run: |
          node - << 'JS'
          const fs = require('fs');
          const path = require('path');

          const postsDir = './blog/posts';
          const outputFile = './blog/posts.json';
          // JSTオフセット（UTC+9）
          const now = new Date(Date.now() + 9 * 60 * 60 * 1000);

          const files = fs.readdirSync(postsDir)
            .filter(f => f.endsWith('.md'));

          const posts = files.map(file => {
            const slug = path.basename(file, '.md');
            const content = fs.readFileSync(path.join(postsDir, file), 'utf-8');

            const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
            let title = slug;
            let date = new Date().toISOString();
            let tags = [];
            let thumbnail = null;
            let thumbnail_credit = null;
            let thumbnail_credit_url = null;

            if (fmMatch) {
              const fm = fmMatch[1];
              const titleMatch = fm.match(/^title:\s*(.+)$/m);
              const dateMatch  = fm.match(/^date:\s*(.+)$/m);
              const tagsMatch  = fm.match(/^tags:\s*\[(.+)\]$/m);
              const tagsBlock  = fm.match(/^tags:\n((?:\s+-\s*.+\n?)+)/m);
              const thumbMatch = fm.match(/^thumbnail:\s*(.+)$/m);
              const creditMatch = fm.match(/^thumbnail_credit:\s*(.+)$/m);
              const creditUrlMatch = fm.match(/^thumbnail_credit_url:\s*(.+)$/m);

              if (titleMatch) title = titleMatch[1].trim().replace(/^["']|["']$/g, '');
              if (dateMatch)  date  = dateMatch[1].trim();
              if (thumbMatch) thumbnail = thumbMatch[1].trim().replace(/^["']|["']$/g, '');
              if (creditMatch) thumbnail_credit = creditMatch[1].trim().replace(/^["']|["']$/g, '');
              if (creditUrlMatch) thumbnail_credit_url = creditUrlMatch[1].trim().replace(/^["']|["']$/g, '');

              if (tagsMatch) {
                tags = tagsMatch[1].split(',').map(t => t.trim().replace(/^["']|["']$/g, ''));
              } else if (tagsBlock) {
                tags = tagsBlock[1].match(/- (.+)/g)
                  .map(t => t.replace('- ', '').trim());
              }
            } else {
              const h1Match = content.match(/^#\s+(.+)$/m);
              if (h1Match) title = h1Match[1].trim();
              const stat = fs.statSync(path.join(postsDir, file));
              date = stat.mtime.toISOString();
            }

            // 予約投稿チェック: dateが未来なら除外
            if (new Date(date) > now) {
              console.log(`Skipping scheduled post: ${slug} (${date})`);
              return null;
            }

            return {
              slug,
              title,
              date,
              tags,
              ...(thumbnail && { thumbnail }),
              ...(thumbnail_credit && { thumbnail_credit }),
              ...(thumbnail_credit_url && { thumbnail_credit_url }),
            };
          }).filter(Boolean);

          // 日時の新しい順にソート
          posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

          fs.writeFileSync(outputFile, JSON.stringify(posts, null, 4));
          console.log(`Generated posts.json with ${posts.length} posts.`);
          JS

      - name: Commit posts.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add blog/posts.json
          git diff --staged --quiet || git commit -m "chore: update posts.json"
          git push